---
- name: fetch the realm(s)
  command: "{{ container_exec_cmd }} radosgw-admin realm pull --rgw-realm={{ item.realm }} --url={{ item.endpoint }} --access-key={{ item.access_key }} --secret={{ item.secret_key }}"
  delegate_to: "{{ groups[mon_group_name][0] }}"
  run_once: true
  with_items: "{{ secondary_realms }}"
  when: secondary_realms is defined

- name: get the period(s)
  command: "{{ container_exec_cmd }} radosgw-admin period get --rgw-realm={{ item.realm }}"
  delegate_to: "{{ groups[mon_group_name][0] }}"
  run_once: true
  with_items: "{{ secondary_realms }}"
  when: secondary_realms is defined

- name: create the default zone
  command: "{{ container_exec_cmd }} radosgw-admin zone create --rgw-realm={{ item.realm }} --rgw-zonegroup={{ item.zonegroup }} --rgw-zone={{ item.zone }} --endpoints={{ item.endpoint }} --access-key={{ item.access_key }} --secret={{ item.secret_key }} --default"
  delegate_to: "{{ groups[mon_group_name][0] }}"
  run_once: true
  with_items: "{{ zones }}"
  when: 
    - zones is defined
    - item.is_master == false and item.is_default == true

- name: create the non-master non-default zone(s)
  command: "{{ container_exec_cmd }} radosgw-admin zone create --rgw-realm={{ item.realm }} --rgw-zonegroup={{ item.zonegroup }} --rgw-zone={{ item.zone }} --endpoints={{ item.endpoint }} --access-key={{ item.access_key }} --secret={{ item.secret_key }}"
  delegate_to: "{{ groups[mon_group_name][0] }}"
  run_once: true
  with_items: "{{ zones }}"
  when: 
    - zones is defined
    - item.is_master == false and item.is_default == false
  notify: update period

- name: add other endpoints to the zone
  command: "{{ container_exec_cmd }} radosgw-admin zone modify --rgw-realm={{ rgw_realm }} --rgw-zonegroup={{ rgw_zonegroup }} --rgw-zone={{ rgw_zone }} --endpoints {{ rgw_multisite_endpoints_list }}"
  delegate_to: "{{ groups[mon_group_name][0] }}"
  when: rgw_multisite_endpoints_list is defined
  notify: update period
